import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">PSFCHome</Link>
        </li>
        <li>
          <Link to="/psfcpamoformodelepagevalidation">
            PSFCPAMOFORmodelepagevalidation
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoformodelepageadmin">
            PSFCPAMOFORmodelepageadmin
          </Link>
        </li>
        <li>
          <Link to="/listecontrat">Listecontrat</Link>
        </li>
        <li>
          <Link to="/psfcpamoformodelepagevalidationcontratsattente">
            PSFCPAMOFORmodelepagevalidationcontratsattente
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoformodelepagevalidationcontratsvalids">
            PSFCPAMOFORmodelepagevalidationcontratsvalids
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoformodelepagevalidationcontratsrejets">
            PSFCPAMOFORmodelepagevalidationcontratsrejets
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoformodelepagevalidationcontratspagevalidationtwo">
            PSFCPAMOFORmodelepagevalidationcontratspageValidationTwo
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoformodelepagevalidationcontratspagevalidationthree">
            PSFCPAMOFORmodelepagevalidationcontratspageValidationThree
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoformodelepagevalidationcontratspagevalidationfour">
            PSFCPAMOFORmodelepagevalidationcontratspageValidationFour
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoformodelepagevalidationcontratspagevalidationone">
            PSFCPAMOFORmodelepagevalidationcontratspageValidationOne
          </Link>
        </li>
        <li>
          <Link to="/psfcsignin">PSFCSignin</Link>
        </li>
        <li>
          <Link to="/psfcseconnecter">PSFCSeconnecter</Link>
        </li>
        <li>
          <Link to="/psfcmdpoublie">PSFCMdpoublie</Link>
        </li>
        <li>
          <Link to="/psfcreinitialisermdp">PSFCReinitialisermdp</Link>
        </li>
        <li>
          <Link to="/psfcprojets">PSFCProjets</Link>
        </li>
        <li>
          <Link to="/pamofor">Pamofor</Link>
        </li>
        <li>
          <Link to="/contrats">Contrats</Link>
        </li>
        <li>
          <Link to="/addcontrat">AddContrat</Link>
        </li>
        <li>
          <Link to="/contratdonationpone">ContratdonationpOne</Link>
        </li>
        <li>
          <Link to="/contratdonationptwo">ContratdonationpTwo</Link>
        </li>
        <li>
          <Link to="/contratdonationpthree">ContratdonationpThree</Link>
        </li>
        <li>
          <Link to="/contratdonationpfour">ContratdonationpFour</Link>
        </li>
        <li>
          <Link to="/contratdonationpfive">ContratdonationpFive</Link>
        </li>
        <li>
          <Link to="/contratdonationpsix">ContratdonationpSix</Link>
        </li>
        <li>
          <Link to="/contratdonationpseven">ContratdonationpSeven</Link>
        </li>
        <li>
          <Link to="/contratdonationpeight">ContratdonationpEight</Link>
        </li>
        <li>
          <Link to="/psfcmenuprofil">PSFCMenuprofil</Link>
        </li>
        <li>
          <Link to="/psfcprofil">PSFCProfil</Link>
        </li>
        <li>
          <Link to="/psfccomptecravecsuccs">PSFCComptecravecsuccs</Link>
        </li>
        <li>
          <Link to="/psfcmdprinitialisavecsuccs">
            PSFCMdprinitialisavecsuccs
          </Link>
        </li>
        <li>
          <Link to="/psfccompteconfirmationmail">
            PSFCCompteconfirmationmail
          </Link>
        </li>
        <li>
          <Link to="/psfccompteconfirmationvalid">
            PSFCCompteconfirmationvalid
          </Link>
        </li>
        <li>
          <Link to="/psfccompteconfirmationechoue">
            PSFCCompteconfirmationechoue
          </Link>
        </li>
        <li>
          <Link to="/addenquete">AddEnquete</Link>
        </li>
        <li>
          <Link to="/enquete">Enquete</Link>
        </li>
        <li>
          <Link to="/psfcpamoforenqpromocontratcontratlocationpthree">
            PSFCPAMOFOREnqPromoContratContratlocationpThree
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoforenqpromocontratcontratlocationpfour">
            PSFCPAMOFOREnqPromoContratContratlocationpFour
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoforenqpromocontratcontratlocationpfive">
            PSFCPAMOFOREnqPromoContratContratlocationpFive
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoforenqpromocontratcontratlocationpsix">
            PSFCPAMOFOREnqPromoContratContratlocationpSix
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoforenqpromocontratcontratlocationpseven">
            PSFCPAMOFOREnqPromoContratContratlocationpSeven
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoforenqpromocontratcontratlocationpeight">
            PSFCPAMOFOREnqPromoContratContratlocationpEight
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoforenqpromocontratcontratlocationpnine">
            PSFCPAMOFOREnqPromoContratContratlocationpNine
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoforenqpromocontratcontratlocationpten">
            PSFCPAMOFOREnqPromoContratContratlocationpTen
          </Link>
        </li>
        <li>
          <Link to="/psfcpamoforenqpromocontratcontratlocationpeleven">
            PSFCPAMOFOREnqPromoContratContratlocationpEleven
          </Link>
        </li>
        <li>
          <Link to="/frame7888">Frame7888</Link>
        </li>
        <li>
          <Link to="/contratventepone">ContratventepOne</Link>
        </li>
        <li>
          <Link to="/contratventeptwo">ContratventepTwo</Link>
        </li>
        <li>
          <Link to="/contratventepthree">ContratventepThree</Link>
        </li>
        <li>
          <Link to="/contratventepfour">ContratventepFour</Link>
        </li>
        <li>
          <Link to="/contratventepfive">ContratventepFive</Link>
        </li>
        <li>
          <Link to="/contratventepsix">ContratventepSix</Link>
        </li>
        <li>
          <Link to="/contratventepseven">ContratventepSeven</Link>
        </li>
        <li>
          <Link to="/contratventepeight">ContratventepEight</Link>
        </li>
        <li>
          <Link to="/contratventepnine">ContratventepNine</Link>
        </li>
        <li>
          <Link to="/contratventepten">ContratventepTen</Link>
        </li>
        <li>
          <Link to="/contratventepeleven">ContratventepEleven</Link>
        </li>
        <li>
          <Link to="/contratventeptwelve">ContratventepTwelve</Link>
        </li>
        <li>
          <Link to="/contratventepthirteen">ContratventepThirteen</Link>
        </li>
        <li>
          <Link to="/contratventepfourteen">ContratventepFourteen</Link>
        </li>
        <li>
          <Link to="/contratventepfifteen">ContratventepFifteen</Link>
        </li>
        <li>
          <Link to="/frame7889">Frame7889</Link>
        </li>
        <li>
          <Link to="/contratmetayagepsix">ContratmetayagepSix</Link>
        </li>
        <li>
          <Link to="/contratmetayagepone">ContratmetayagepOne</Link>
        </li>
        <li>
          <Link to="/contratmetayageptwo">ContratmetayagepTwo</Link>
        </li>
        <li>
          <Link to="/contratmetayagepthree">ContratmetayagepThree</Link>
        </li>
        <li>
          <Link to="/contratmetayagepfour">ContratmetayagepFour</Link>
        </li>
        <li>
          <Link to="/contratventepfiveone">ContratventepFiveOne</Link>
        </li>
        <li>
          <Link to="/contratmetayagepseven">ContratmetayagepSeven</Link>
        </li>
        <li>
          <Link to="/contratmetayagepeight">ContratmetayagepEight</Link>
        </li>
        <li>
          <Link to="/contratmetayagepnine">ContratmetayagepNine</Link>
        </li>
        <li>
          <Link to="/contratmetayagepten">ContratmetayagepTen</Link>
        </li>
        <li>
          <Link to="/contratpretpone">ContratpretpOne</Link>
        </li>
        <li>
          <Link to="/contratpretptwo">ContratpretpTwo</Link>
        </li>
        <li>
          <Link to="/contratpretpthree">ContratpretpThree</Link>
        </li>
        <li>
          <Link to="/contratpretpfour">ContratpretpFour</Link>
        </li>
        <li>
          <Link to="/contratpretpfive">ContratpretpFive</Link>
        </li>
        <li>
          <Link to="/contratpretpsix">ContratpretpSix</Link>
        </li>
        <li>
          <Link to="/contratpretpseven">ContratpretpSeven</Link>
        </li>
        <li>
          <Link to="/contratpretpten">ContratpretpTen</Link>
        </li>
        <li>
          <Link to="/contratpretpeight">ContratpretpEight</Link>
        </li>
        <li>
          <Link to="/contratpretpnine">ContratpretpNine</Link>
        </li>
        <li>
          <Link to="/contratrecoltepone">ContratrecoltepOne</Link>
        </li>
        <li>
          <Link to="/contratrecoleptwo">ContratrecolepTwo</Link>
        </li>
        <li>
          <Link to="/contratrecolepthree">ContratrecolepThree</Link>
        </li>
        <li>
          <Link to="/contratrecolepfour">ContratrecolepFour</Link>
        </li>
        <li>
          <Link to="/contratrecolepfive">ContratrecolepFive</Link>
        </li>
        <li>
          <Link to="/contratrecoltepsix">ContratrecoltepSix</Link>
        </li>
        <li>
          <Link to="/contratrecoltepseven">ContratrecoltepSeven</Link>
        </li>
        <li>
          <Link to="/contratrecoltepeight">ContratrecoltepEight</Link>
        </li>
        <li>
          <Link to="/contratrecoltepnine">ContratrecoltepNine</Link>
        </li>
        <li>
          <Link to="/contratrecoltepten">ContratrecoltepTen</Link>
        </li>
        <li>
          <Link to="/contratrecoltepeleven">ContratrecoltepEleven</Link>
        </li>
        <li>
          <Link to="/contratrecolteptwelve">ContratrecoltepTwelve</Link>
        </li>
        <li>
          <Link to="/contratplantationpone">ContratplantationpOne</Link>
        </li>
        <li>
          <Link to="/contratplantationptwo">ContratplantationpTwo</Link>
        </li>
        <li>
          <Link to="/contratplantationpthree">ContratplantationpThree</Link>
        </li>
        <li>
          <Link to="/contratplantationpfour">ContratplantationpFour</Link>
        </li>
        <li>
          <Link to="/contratplantationpfive">ContratplantationpFive</Link>
        </li>
        <li>
          <Link to="/contratplantationpsix">ContratplantationpSix</Link>
        </li>
        <li>
          <Link to="/contratplantationpseven">ContratplantationpSeven</Link>
        </li>
        <li>
          <Link to="/contratplantationpeight">ContratplantationpEight</Link>
        </li>
        <li>
          <Link to="/contratplantationpnine">ContratplantationpNine</Link>
        </li>
        <li>
          <Link to="/contratplantationpten">ContratplantationpTen</Link>
        </li>
        <li>
          <Link to="/contratplantationpeleven">ContratplantationpEleven</Link>
        </li>
        <li>
          <Link to="/contratplantationptwelve">ContratplantationpTwelve</Link>
        </li>
        <li>
          <Link to="/contratterrepone">ContratterrepOne</Link>
        </li>
        <li>
          <Link to="/contratterreptwo">ContratterrepTwo</Link>
        </li>
        <li>
          <Link to="/contratterrepthree">ContratterrepThree</Link>
        </li>
        <li>
          <Link to="/contratterrepfour">ContratterrepFour</Link>
        </li>
        <li>
          <Link to="/contratterrepfive">ContratterrepFive</Link>
        </li>
        <li>
          <Link to="/contratterrepsix">ContratterrepSix</Link>
        </li>
        <li>
          <Link to="/contratterrepseven">ContratterrepSeven</Link>
        </li>
        <li>
          <Link to="/contratterrepeight">ContratterrepEight</Link>
        </li>
        <li>
          <Link to="/contratterrepnine">ContratterrepNine</Link>
        </li>
        <li>
          <Link to="/contratterrepten">ContratterrepTen</Link>
        </li>
        <li>
          <Link to="/contratterrepeleven">ContratterrepEleven</Link>
        </li>
        <li>
          <Link to="/contratterreptwelve">ContratterrepTwelve</Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepone">ContratmiseengarantiepOne</Link>
        </li>
        <li>
          <Link to="/contratmiseengarantieponetwo">
            ContratmiseengarantiepOneTwo
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantieptwo">ContratmiseengarantiepTwo</Link>
        </li>
        <li>
          <Link to="/contratmiseengarantieptwotwo">
            ContratmiseengarantiepTwoTwo
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepthree">
            ContratmiseengarantiepThree
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepthreeone">
            ContratmiseengarantiepThreeOne
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepfourtwo">
            ContratmiseengarantiepFourTwo
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepfourone">
            ContratmiseengarantiepFourOne
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepfive">
            ContratmiseengarantiepFive
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepfivetwo">
            ContratmiseengarantiepFiveTwo
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepsix">ContratmiseengarantiepSix</Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepseven">
            ContratmiseengarantiepSeven
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepeight">
            ContratmiseengarantiepEight
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepnine">
            ContratmiseengarantiepNine
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepten">ContratmiseengarantiepTen</Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepeleven">
            ContratmiseengarantiepEleven
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantieponeone">
            ContratmiseengarantiepOneOne
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantieptwoone">
            ContratmiseengarantiepTwoOne
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepthreetwo">
            ContratmiseengarantiepThreeTwo
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepfour">
            ContratmiseengarantiepFour
          </Link>
        </li>
        <li>
          <Link to="/contratmiseengarantiepfiveone">
            ContratmiseengarantiepFiveOne
          </Link>
        </li>
        <li>
          <Link to="/contratjacherepsix">ContratjacherepSix</Link>
        </li>
        <li>
          <Link to="/contratjacherepseven">ContratjacherepSeven</Link>
        </li>
        <li>
          <Link to="/contratjacherepeight">ContratjacherepEight</Link>
        </li>
        <li>
          <Link to="/contratjacherepnine">ContratjacherepNine</Link>
        </li>
        <li>
          <Link to="/contratjacherepten">ContratjacherepTen</Link>
        </li>
        <li>
          <Link to="/contratjacherepeleven">ContratjacherepEleven</Link>
        </li>
        <li>
          <Link to="/contratcessionpone">ContratcessionpOne</Link>
        </li>
        <li>
          <Link to="/contratcessionptwo">ContratcessionpTwo</Link>
        </li>
        <li>
          <Link to="/contratcessionptwoone">ContratcessionpTwoOne</Link>
        </li>
        <li>
          <Link to="/contratcessionpthree">ContratcessionpThree</Link>
        </li>
        <li>
          <Link to="/contratcessionpfour">ContratcessionpFour</Link>
        </li>
        <li>
          <Link to="/contratcessionpfive">ContratcessionpFive</Link>
        </li>
        <li>
          <Link to="/contratcessionpseven">ContratcessionpSeven</Link>
        </li>
        <li>
          <Link to="/contratcessionpeight">ContratcessionpEight</Link>
        </li>
        <li>
          <Link to="/contratcessionpnine">ContratcessionpNine</Link>
        </li>
        <li>
          <Link to="/cf1one">CF1One</Link>
        </li>
        <li>
          <Link to="/cf1two">CF1Two</Link>
        </li>
        <li>
          <Link to="/cf1">CF1</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
